Fix typos in CP Power Iteration
tensorly/tensorly pull request #244
Opened 2021-03-12 22:04 UTC by chrisyeh96

and remove unused import

2021-03-13 11:34 UTC, JeanKossaifi requested changes
Thanks @chrisyeh96, looks good, just made some suggestions to avoid using `np.inf`.
After this I think it's ready to merge.

2021-03-13 11:34 UTC, JeanKossaifi commented on tensorly/decomposition/_symmetric_cp.py
> +    best_score = -np.inf
Best not to mix numpy in the calculations, let's just not initialize best_score here.

2021-03-13 11:34 UTC, JeanKossaifi commented on tensorly/decomposition/_symmetric_cp.py
>      for _ in range(n_repeat):
```suggestion
    for i in range(n_repeat):
```

2021-03-13 11:34 UTC, JeanKossaifi commented on tensorly/decomposition/_symmetric_cp.py
>          if score > best_score:
```suggestion
        if (i == 0) or (score > best_score):
```

2021-03-14 00:18 UTC, chrisyeh96 commented
@JeanKossaifi

I made the proposed fixes. I also made the same fixes in the general `power_iteration()` method (for non-symmetric tensors).

2021-03-14 12:08 UTC, JeanKossaifi commented
@chrisyeh96 this is great, thank you! Merging.

2021-03-14 12:10 UTC, merged